spring:
  application:
    name: Catalogo-De-Livros
  datasource:
    url: jdbc:postgresql://localhost:5432/livraria
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update